<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'user.getProfile',
                'label' => '用户自身信息',
                'description' => '查看用户自身信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ], [
                'id' => 2,
                'name' => 'user.profileUpdate',
                'label' => '修改用户自身信息',
                'description' => '修改用户自身信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ], [
                'id' => 3,
                'name' => 'user.index',
                'label' => '查看所有员工',
                'description' => '查看所有员工信息，包括所属部门',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 4,
                'name' => 'user.edit',
                'label' => '修改员工',
                'description' => '修改员工信息，包括所属部门，权限等',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 5,
                'name' => 'user.create',
                'label' => '新增员工',
                'description' => '新增员工，包括所属部门，权限等',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 6,
                'name' => 'user.destroy',
                'label' => '删除员工',
                'description' => '删除某个员工',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 7,
                'name' => 'leave.monthLeaves',
                'label' => '查看员工的请假信息',
                'description' => '查看员工的请假信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 8,
                'name' => 'user.index',
                'label' => '查看所有员工',
                'description' => '查看所有员工信息，包括所属部门',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 9,
                'name' => 'group.index',
                'label' => '查看部门',
                'description' => '查看所有部门信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 10,
                'name' => 'group.edit',
                'label' => '编辑部门',
                'description' => '编辑部门，包括部门信息，拥有权限',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 11,
                'name' => 'group.create',
                'label' => '新增部门',
                'description' => '新增部门，分配部门权限',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 12,
                'name' => 'permission.index',
                'label' => '权限信息',
                'description' => '权限信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 13,
                'name' => 'permission.store',
                'label' => '新增权限',
                'description' => '新增权限',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 14,
                'name' => 'permission.update',
                'label' => '权限修改',
                'description' => '权限修改',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 15,
                'name' => 'permission.destroy',
                'label' => '权限删除',
                'description' => '权限删除',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 16,
                'name' => 'post.edit',
                'label' => '新闻公告修改',
                'description' => '新闻公告修改',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 17,
                'name' => 'post.create',
                'label' => '新闻公告新增',
                'description' => '新闻公告新增',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 18,
                'name' => 'post.destroy',
                'label' => '新闻公告删除',
                'description' => '新闻公告删除',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 19,
                'name' => 'server.index',
                'label' => '查看服务器',
                'description' => '查看服务器',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 20,
                'name' => 'server.edit',
                'label' => '服务器修改',
                'description' => '修改服务器',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 21,
                'name' => 'server.create',
                'label' => '新增服务器',
                'description' => '新增服务器',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 22,
                'name' => 'server.destroy',
                'label' => '服务器删除',
                'description' => '删除服务器',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 23,
                'name' => 'country.index',
                'label' => '查看国家',
                'description' => '查看国家',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 24,
                'name' => 'country.edit',
                'label' => '国家修改',
                'description' => '修改国家',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 25,
                'name' => 'country.create',
                'label' => '新增国家',
                'description' => '新增国家',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 26,
                'name' => 'country.destroy',
                'label' => '国家删除',
                'description' => '删除国家',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 27,
                'name' => 'brand.index',
                'label' => '查看网站品牌',
                'description' => '查看网站品牌',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 28,
                'name' => 'brand.edit',
                'label' => '网站品牌修改',
                'description' => '修改网站品牌',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 29,
                'name' => 'brand.create',
                'label' => '新增网站品牌',
                'description' => '新增网站品牌',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 30,
                'name' => 'brand.destroy',
                'label' => '网站品牌删除',
                'description' => '删除网站品牌',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 31,
                'name' => 'adStatus.index',
                'label' => '查看广告状态',
                'description' => '查看广告状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 32,
                'name' => 'adStatus.edit',
                'label' => '广告状态修改',
                'description' => '修改广告状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 33,
                'name' => 'adStatus.create',
                'label' => '新增广告状态',
                'description' => '新增广告状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 34,
                'name' => 'adStatus.destroy',
                'label' => '广告状态删除',
                'description' => '删除广告状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 35,
                'name' => 'websiteStatus.index',
                'label' => '查看网站状态',
                'description' => '查看网站状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 36,
                'name' => 'websiteStatus.edit',
                'label' => '网站状态修改',
                'description' => '修改网站状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 37,
                'name' => 'websiteStatus.create',
                'label' => '新增网站状态',
                'description' => '新增网站状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 38,
                'name' => 'websiteStatus.destroy',
                'label' => '网站状态删除',
                'description' => '删除网站状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 39,
                'name' => 'host.index',
                'label' => '查看Host',
                'description' => '查看Host',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 40,
                'name' => 'host.edit',
                'label' => 'Host修改',
                'description' => '修改Host',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 41,
                'name' => 'host.create',
                'label' => '新增Host',
                'description' => '新增Host',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 42,
                'name' => 'host.destroy',
                'label' => 'Host删除',
                'description' => '删除Host',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 43,
                'name' => 'website.index',
                'label' => '查看网站',
                'description' => '查看网站',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 44,
                'name' => 'website.edit',
                'label' => '网站修改',
                'description' => '修改网站',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 45,
                'name' => 'website.create',
                'label' => '新增网站',
                'description' => '新增网站',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 46,
                'name' => 'website.destroy',
                'label' => '网站删除',
                'description' => '删除网站',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 47,
                'name' => 'orderStatus.index',
                'label' => '查看付款前订单状态',
                'description' => '查看付款前订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 48,
                'name' => 'orderStatus.edit',
                'label' => '付款前订单状态修改',
                'description' => '修改付款前订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 49,
                'name' => 'orderStatus.create',
                'label' => '新增付款前订单状态',
                'description' => '新增付款前订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 50,
                'name' => 'orderStatus.destroy',
                'label' => '付款前订单状态删除',
                'description' => '删除付款前订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 51,
                'name' => 'orderPayAfterStatus.index',
                'label' => '查看付款后订单状态',
                'description' => '查看付款后订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 52,
                'name' => 'orderPayAfterStatus.edit',
                'label' => '付款后订单状态修改',
                'description' => '修改付款后订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 53,
                'name' => 'orderPayAfterStatus.create',
                'label' => '新增付款后订单状态',
                'description' => '新增付款后订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 54,
                'name' => 'orderPayAfterStatus.destroy',
                'label' => '付款后订单状态删除',
                'description' => '删除付款后订单状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 55,
                'name' => 'express.index',
                'label' => '查看货运方式',
                'description' => '查看货运方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 56,
                'name' => 'express.edit',
                'label' => '货运方式修改',
                'description' => '修改货运方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 57,
                'name' => 'express.create',
                'label' => '新增货运方式',
                'description' => '新增货运方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 58,
                'name' => 'express.destroy',
                'label' => '货运方式删除',
                'description' => '删除货运方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 59,
                'name' => 'expressCompany.index',
                'label' => '查看快递公司',
                'description' => '查看快递公司',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 60,
                'name' => 'expressCompany.edit',
                'label' => '快递公司修改',
                'description' => '修改快递公司',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 61,
                'name' => 'expressCompany.create',
                'label' => '新增快递公司',
                'description' => '新增快递公司',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 62,
                'name' => 'expressCompany.destroy',
                'label' => '快递公司删除',
                'description' => '删除快递公司',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 63,
                'name' => 'customerService.order',
                'label' => '客服部首页',
                'description' => '客服部首页',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 64,
                'name' => 'customerService.update',
                'label' => '客服部修改订单信息',
                'description' => '',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 65,
                'name' => 'orderDepartment.order',
                'label' => '订货部首页',
                'description' => '订货部首页，订单及产品信息',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 66,
                'name' => 'orderDepartment.productsToPurchaseGroup',
                'label' => '产品加入订货分组',
                'description' => '订货部，产品加入订货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 67,
                'name' => 'purchaseGroup.index',
                'label' => '查看订货分组',
                'description' => '查看订货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 68,
                'name' => 'purchaseGroup.edit',
                'label' => '订货分组修改',
                'description' => '修改订货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 69,
                'name' => 'purchaseGroup.create',
                'label' => '新增订货分组',
                'description' => '新增订货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 70,
                'name' => 'purchaseGroup.destroy',
                'label' => '订货分组删除',
                'description' => '删除订货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 71,
                'name' => 'deliveryDepartment.order',
                'label' => '发货部首页',
                'description' => '发货部首页',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 72,
                'name' => 'deliveryDepartment.exportdhl',
                'label' => '导出dhl',
                'description' => '导出dhl',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 73,
                'name' => 'deliveryDepartment.barCode',
                'label' => '打印条形码',
                'description' => '打印条形码',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 74,
                'name' => 'deliveryDepartment.productsToShippingGroup',
                'label' => '产品加入发货分组',
                'description' => '发货部，产品加入发货分组',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 75,
                'name' => 'supplier.index',
                'label' => '查看供应商',
                'description' => '查看供应商',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 76,
                'name' => 'supplier.edit',
                'label' => '供应商修改',
                'description' => '修改供应商',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 77,
                'name' => 'supplier.create',
                'label' => '新增供应商',
                'description' => '新增供应商',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 78,
                'name' => 'supplier.destroy',
                'label' => '供应商删除',
                'description' => '删除供应商',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 79,
                'name' => 'orderCategory.index',
                'label' => '查看订单产品分类',
                'description' => '查看订单产品分类',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 80,
                'name' => 'orderCategory.edit',
                'label' => '订单产品分类修改',
                'description' => '修改订单产品分类',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 81,
                'name' => 'orderCategory.create',
                'label' => '新增订单产品分类',
                'description' => '新增订单产品分类',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 82,
                'name' => 'orderCategory.destroy',
                'label' => '订单产品分类删除',
                'description' => '删除订单产品分类',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 83,
                'name' => 'mall.index',
                'label' => '查看店铺',
                'description' => '查看店铺',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 84,
                'name' => 'mall.edit',
                'label' => '店铺修改',
                'description' => '修改店铺',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 85,
                'name' => 'mall.create',
                'label' => '新增店铺',
                'description' => '新增店铺',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 86,
                'name' => 'mall.destroy',
                'label' => '店铺删除',
                'description' => '删除店铺',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 87,
                'name' => 'mallStatus.index',
                'label' => '查看店铺状态',
                'description' => '查看店铺状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 88,
                'name' => 'mallStatus.edit',
                'label' => '店铺状态修改',
                'description' => '修改店铺状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 89,
                'name' => 'mallStatus.create',
                'label' => '新增店铺状态',
                'description' => '新增店铺状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 90,
                'name' => 'mallStatus.destroy',
                'label' => '店铺状态删除',
                'description' => '删除店铺状态',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 91,
                'name' => 'mallPayType.index',
                'label' => '查看付款方式',
                'description' => '查看付款方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 92,
                'name' => 'mallPayType.edit',
                'label' => '付款方式修改',
                'description' => '修改付款方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 93,
                'name' => 'mallPayType.create',
                'label' => '新增付款方式',
                'description' => '新增付款方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 94,
                'name' => 'mallPayType.destroy',
                'label' => '付款方式删除',
                'description' => '删除付款方式',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'id' => 95,
                'name' => 'stock.index',
                'label' => '产品库存首页',
                'description' => '产品库存首页',
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ]
        ]);
    }
}
